on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test_spacecheck:
    name: Test spacecheck.sh
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v4.1.1

      - name: Create folders and base files
        run: |
          mkdir sop

          for i in {1..5}
          do
            mkdir -p sop/subdir$i
          done

          for i in {1..5}
          do
            for j in {1..5}
            do
              touch sop/subdir$i/file$j.txt
            done
          done

          touch sop/json1.json
          touch sop/json2.json

      - name: Modify some files
        run: |
          touch -a -m -t 202301010000.00 sop/subdir1/file1.txt
          touch -a -m -t 202306010000.00 sop/subdir2/file1.txt
          touch -a -m -t 202211010000.00 sop/subdir3/file1.txt

          dd if=/dev/zero of=sop/subdir3/file2.txt bs=1M count=1
          dd if=/dev/zero of=sop/subdir4/file2.txt bs=1M count=2
          dd if=/dev/zero of=sop/subdir5/file2.txt bs=1M count=3

          dd if=/dev/zero of=sop/json2.json bs=1M count=3
          touch -a -m -t 202211010000.00 sop/json2.json

      - name: Set execution permissions
        run: chmod +x ./spacecheck.sh

      - name: Run spacecheck.sh, with no parameters
        run: ./spacecheck.sh sop

      - name: Run spacecheck.sh, reversed
        run: ./spacecheck.sh -r sop

      - name: Run spacecheck.sh, ordered by name
        run: ./spacecheck.sh -a sop

      - name: Run spacecheck.sh, ordered by name and reversed
        run: ./spacecheck.sh -ar sop

      - name: Run spacecheck.sh, with limited output
        run: ./spacecheck.sh -l 2 sop

      - name: Run spacecheck.sh, filtered by date
        run: ./spacecheck.sh -d "Dec 1 2022 10:00" sop

      - name: Run spacecheck.sh, filtered by regex (.json)
        run: ./spacecheck.sh -n ".*json" sop

      - name: Run spacecheck.sh, filtered by minimum size
        run: ./spacecheck.sh -s 2000000 sop

      - name: Run spacecheck.sh, filtered by everything
        run: ./spacecheck.sh -ar -l 2 -d "Dec 1 2022 10:00" -n ".*json" -s 2000000 sop
  
  test_spacerate:
    name: Test spacerate.sh
    runs-on: ubuntu-latest
    steps:
      - name: Create base files
        run: |
          echo "SIZE       NAME 20231104 sop
          NA         sop/main/if what
          64         sop/main/what if
          64         sop/whatever
          6372       sop/main
          13635108   sop
          11         a" > sr1.txt

          echo "SIZE       NAME 20231105 -r sop
          NA         sop/main/if what
          64         sop/main/what if
          64         sop/whatever
          6408       sop/main
          12780      sop
          1234       b" > sr2.txt
      
      - name: Run spacerate.sh, with no parameters
        run: ./spacerate.sh sr1.txt sr2.txt
      
      - name: Run spacerate.sh, reversed
        run: ./spacerate.sh -r sr1.txt sr2.txt
      
      - name: Run spacerate.sh, ordered by name
        run: ./spacerate.sh -a sr1.txt sr2.txt
      
      - name: Run spacerate.sh, ordered by name and reversed
        run: ./spacerate.sh -ar sr1.txt sr2.txt
